module.exports = {
  allow: [
    "360Spider",
    "360Spider-Image",
    "360Spider-Video",
    "AdsBot-Google",
    "AdsBot-Google-Mobile",
    "AdsBot-Google-Mobile-Apps",
    "adidxbot",
    "Applebot",
    "AppleNewsBot",
    "Baiduspider",
    "Baiduspider-image",
    "Baiduspider-news",
    "Baiduspider-video",
    "bingbot",
    "BingPreview",
    "BublupBot",
    "CCBot",
    "Cliqzbot",
    "coccoc",
    "coccocbot-image",
    "coccocbot-web",
    "Daumoa",
    "Dazoobot",
    "DeuSu",
    "DuckDuckBot",
    "DuckDuckGo-Favicons-Bot",
    "EuripBot",
    "Exploratodo",
    "Facebot",
    "Feedly",
    "Findxbot",
    "Googlebot",
    "Googlebot-Image",
    "Googlebot-Mobile",
    "Googlebot-News",
    "Googlebot-Video",
    "HaoSouSpider",
    "ichiro",
    "istellabot",
    "JikeSpider",
    "Lycos",
    "Mail.Ru",
    "Mediapartners-Google",
    "MojeekBot",
    "msnbot",
    "msnbot-media",
    "OrangeBot",
    "Pinterest",
    "Plukkie",
    "Qwantify",
    "Rambler",
    "SeznamBot",
    "Sosospider",
    "Slurp",
    "Sogou blog",
    "Sogou inst spider",
    "Sogou News Spider",
    "Sogou Orion spider",
    "Sogou spider2",
    "Sogou web spider",
    "SputnikBot",
    "Teoma",
    "Twitterbot",
    "wotbox",
    "yacybot",
    "Yandex",
    "YandexMobileBot",
    "Yeti",
    "YioopBot",
    "yoozBot",
    "YoudaoBot",
  ],
  disallow: ["*"],
}
