apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  type: NodePort
  ports:
      # pod port
    - targetPort: 80
      # service port on pod-side 
      port: 80
      # service
      nodePort: 30004
  selector:
    # same label(s) as the pod
    app: myapp
    # type: front-end
  # THIS needs more research
  externalIPs:
    - 1.2.3.110