apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: voting-app-box
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        # app listens on port 80
        - containerPort: 80