const SENTENCES = 'SENTENCES';
const UPDATE_DISPLAY_TEXT_FROM_AREA = 'UPDATE_DISPLAY_TEXT_FROM_AREA';
const WORD_LENGTH = 'WORD_LENGTH';
const TEXT = 'TEXT';
const MAX_WORDS = 'MAX_WORDS';
const THEME = 'THEME';
const DONE_FETCHING_TEXT = 'DONE_FETCHING_TEXT';
const SET_AREA_DATA = 'SET_AREA_DATA';

export {
  SENTENCES,
  UPDATE_DISPLAY_TEXT_FROM_AREA,
  WORD_LENGTH,
  TEXT,
  MAX_WORDS,
  THEME,
  DONE_FETCHING_TEXT,
  SET_AREA_DATA
}