apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    name: voting-app-deploy
    app: demo-voting-app
spec:
  # to save resources on my laptop!
  replicas: 1
  selector:
    matchLabels:
      # match the voting-app pod def file
      name: voting-app-pod
      app: demo-voting-app
  template:
    # metadata taken directly from pod def file
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: voting-app-box
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            # app listens on port 80
            - containerPort: 80