apiVersion: v1
kind: ReplicationController
metadata:
  name: first-rc
  labels:
     app: rc-app
     type: front-end
spec:
  # define the replica count
  replicas: 3
  # pod template: using metadata + spec of a pod
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx