apiVersion: apps/v1
kind: ReplicaSet
metadata:
  # must be lowercase
  name: first-replica-set
  labels:
     app: replica-set-app
spec:
  selector:
    matchLabels:
      app: replica-set-app
  replicas: 3
  template:
    metadata:
      name: nginx-from-replica-set
      labels:
        app: replica-set-app
    spec:
      containers:
        - name: nginx-container
          image: nginx