apiVersion: apps/v1
kind: Deployment
metadata:
  # must be lowercase
  name: first-deployment
  labels:
     tier: frontend
     app: nginx
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      name: nginx-from-replica-set
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-box
          image: nginx